direction: up

Integer: Integer {
  shape: oval
  style.fill: "#e2e3e5"
}
Natural: Natural {
  shape: oval
  style.fill: "#d4edda"
}
Nonpositive: Nonpositive {
  shape: oval
  style.fill: "#fff3cd"
}
AddOne: "AddOne\<N\>"
Zero: Zero {
  style.fill: "#cce5ff"
}
SubOne: "SubOne\<N\>"

Natural -> Integer
Nonpositive -> Integer
AddOne -> Natural {
  style.stroke-dash: 5
}
Zero -> Natural
Zero -> Nonpositive
SubOne -> Nonpositive {
  style.stroke-dash: 5
}
